version: '3.1'
services:
  ims-mysql:
    container_name: ims-mysql
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_DATABASE: ims-image-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_ROOT_HOST: '%'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql-data-volume:/var/lib/mysql

  ims-image-app:
    container_name: ims-image-app
    restart: always
    depends_on: 
      - ims-mysql
    restart: always
    environment:
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_DATASOURCE_URL: jdbc:mysql://ims-mysql:3306/ims-image-db?createDatabaseIfNotExist=true&useSSL=false  
    # will build Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8008:8008'
    # expose:
    #   - '8009'
    command: "mvn clean spring-boot:run"  

# Names our volume
volumes:
  mysql-data-volume:

